name: Deploy to kind Cluster

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'The environment to deploy to'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todoapp:${{ github.sha }}

      - name: Set up kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1

      - name: Create kind cluster
        run: kind create cluster --config=cluster.yml

      - name: Verify kind cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Download helm package
        uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - name: Helm install dry-run
        run: helm install --dry-run --debug todoapp ./*.tgz

      - name: Helm upgrade install
        run: helm upgrade --install todoapp ./*.tgz --atomic
