name: Deploy to Kind

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          mv ./kind /usr/local/bin/kind

      - name: Create kind cluster
        run: kind create cluster --config=cluster.yml

      - name: Helm install dry-run
        run: helm install --dry-run todoapp ./helm-charts/todoapp

      - name: Helm upgrade install
        run: helm upgrade --install todoapp ./helm-charts/todoapp --atomic

      - name: Verify deployment
        run: kubectl get pods -n default
